#!/bin/bash -e

if [ -z "$TIMEOUT" ] ; then
    TIMEOUT=86400
fi

if [ -z "$AWS_ACCESS_KEY_ID" ] ; then
    echo "AWS_ACCESS_KEY_ID not specified"
    exit 1
fi

if [ -z "$AWS_SECRET_ACCESS_KEY" ] ; then
    echo "AWS_SECRET_ACCESS_KEY not specified"
    exit 1
fi

if [ -z "$BUCKET" ] ; then
    echo "BUCKET not specified"
    exit 1
fi

DATADIR="/data"

backup_and_stream_to_s3() {
  while true
  do
    echo "Clean"
    rm -rf /backup/*
    echo "Backup"
    cp -r $DATADIR/* /backup

    BACKUP=`date +"%Y-%m-%d_%H-%M-%S"`

    tar -cf /backup/$BACKUP.tar /backup/*
    gzip -7 /backup/$BACKUP.tar

    echo "Upload $BACKUP"
    aws s3 cp "/backup/$BACKUP.tar.gz" $BUCKET/$BACKUP.tar.gz

    echo "Sleep"
    sleep $TIMEOUT
  done
}

backup_and_stream_to_s3

wait
